module Compiler.Generated

import IdrisPaths
import Libraries.Data.Version

export
version : Version
version with (idrisVersion)
 version | (s,"") = MkVersion s Nothing
 version | (s,t) = MkVersion s (Just t)

export
generatedString : String -> String
generatedString backend =
  "@" ++ "generated by Idris/TTImp " ++ (show version) ++ ", " ++ backend ++ " backend"
